versions:
  "17.0":
    folder: meson
  "16.3":
    folder: all
  "16.2":
    folder: all
  "16.1":
    folder: all
  "15.7":
    folder: all
  "15.6":
    folder: all
  "15.5":
    folder: all
  "15.4":
    folder: all
  "15.3":
    folder: all
  "14.9":
    folder: all
