versions:
  "4.0.3.4":
    folder: all
  "4.0.3.3":
    folder: all
  "4.0.3.2":
    folder: all
  "4.0.3.1":
    folder: all
  "4.0.3":
    folder: all
  "4.0.2":
    folder: all
  "4.0.1":
    folder: all
